import React from "react";

export default function page() {
  return (
    <section>
      <main className="max-w-[1000px] mx-auto px-4 py-12 md:py-20 flex flex-col items-center">
        <div className="w-full mb-10 text-center md:text-left">
          <h1 className="text-[#101719] dark:text-white text-4xl md:text-5xl font-black leading-tight tracking-[-0.033em] mb-4">
            Protecting your research.
          </h1>
          <p className="text-[#57818e] dark:text-slate-400 text-lg max-w-2xl">
            ScholarPublish uses two-factor authentication to ensure that your
            manuscripts and peer reviews remain confidential and secure.
          </p>
        </div>
        <div className="w-full flex flex-col lg:flex-row gap-12 items-start">
          <div className="w-full lg:w-3/5 bg-white dark:bg-slate-800 p-8 rounded-xl shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-[#e9eff1] dark:border-slate-700">
            <div className="flex flex-col items-center text-center mb-8">
              <div className="w-20 h-20 bg-primary/10 rounded-full flex items-center justify-center mb-4">
                <span className="material-symbols-outlined text-4xl text-primary">
                  phonelink_lock
                </span>
              </div>
              <h3 className="text-[#101719] dark:text-white text-xl font-bold mb-2">
                Two-Factor Authentication
              </h3>
              <p className="text-sm text-[#57818e] dark:text-slate-400">
                Enter the 6-digit code sent to your registered mobile device or
                generated by your authenticator app.
              </p>
            </div>
            <form className="space-y-8">
              <div className="flex justify-between gap-2 max-w-sm mx-auto">
                <input
                  className="otp-input w-12 h-14 text-center text-2xl font-bold rounded-lg border-[#d3e0e4] dark:border-slate-600 bg-background-light dark:bg-slate-900"
                  inputmode="numeric"
                  maxlength="1"
                  pattern="[0-9]*"
                  required=""
                  type="text"
                />
                <input
                  className="otp-input w-12 h-14 text-center text-2xl font-bold rounded-lg border-[#d3e0e4] dark:border-slate-600 bg-background-light dark:bg-slate-900"
                  inputmode="numeric"
                  maxlength="1"
                  pattern="[0-9]*"
                  required=""
                  type="text"
                />
                <input
                  className="otp-input w-12 h-14 text-center text-2xl font-bold rounded-lg border-[#d3e0e4] dark:border-slate-600 bg-background-light dark:bg-slate-900"
                  inputmode="numeric"
                  maxlength="1"
                  pattern="[0-9]*"
                  required=""
                  type="text"
                />
                <input
                  className="otp-input w-12 h-14 text-center text-2xl font-bold rounded-lg border-[#d3e0e4] dark:border-slate-600 bg-background-light dark:bg-slate-900"
                  inputmode="numeric"
                  maxlength="1"
                  pattern="[0-9]*"
                  required=""
                  type="text"
                />
                <input
                  className="otp-input w-12 h-14 text-center text-2xl font-bold rounded-lg border-[#d3e0e4] dark:border-slate-600 bg-background-light dark:bg-slate-900"
                  inputmode="numeric"
                  maxlength="1"
                  pattern="[0-9]*"
                  required=""
                  type="text"
                />
                <input
                  className="otp-input w-12 h-14 text-center text-2xl font-bold rounded-lg border-[#d3e0e4] dark:border-slate-600 bg-background-light dark:bg-slate-900"
                  inputmode="numeric"
                  maxlength="1"
                  pattern="[0-9]*"
                  required=""
                  type="text"
                />
              </div>
              <div className="space-y-4">
                <button
                  className="w-full bg-primary hover:bg-primary/90 text-white font-bold h-14 rounded-lg text-lg transition-all shadow-lg shadow-primary/20 flex items-center justify-center gap-2"
                  type="submit"
                >
                  Verify and Log In
                  <span className="material-symbols-outlined text-xl">
                    verified_user
                  </span>
                </button>
                <div className="flex flex-col items-center gap-3">
                  <button
                    className="text-sm font-bold text-primary hover:underline"
                    type="button"
                  >
                    Resend Code
                  </button>
                  <button
                    className="text-sm font-medium text-[#57818e] dark:text-slate-400 hover:text-primary"
                    type="button"
                  >
                    Try another method
                  </button>
                </div>
              </div>
            </form>
          </div>
          <div className="w-full lg:w-2/5 flex flex-col gap-6">
            <div className="bg-primary/5 dark:bg-primary/10 border border-primary/10 rounded-xl p-6">
              <div className="flex items-center gap-3 mb-4">
                <span className="material-symbols-outlined text-primary text-3xl">
                  security
                </span>
                <h4 className="font-bold text-[#101719] dark:text-white">
                  Security Tips
                </h4>
              </div>
              <p className="text-sm text-[#57818e] dark:text-slate-400 leading-relaxed mb-4">
                To keep your account secure, please follow these best practices
                for academic integrity and data protection.
              </p>
              <ul className="space-y-3">
                <li className="flex gap-2 text-xs text-[#57818e] dark:text-slate-400">
                  <span className="material-symbols-outlined text-primary text-base">
                    lock
                  </span>
                  Never share your 2FA code with anyone, including
                  ScholarPublish staff.
                </li>
                <li className="flex gap-2 text-xs text-[#57818e] dark:text-slate-400">
                  <span className="material-symbols-outlined text-primary text-base">
                    devices
                  </span>
                  Use a trusted personal device for receiving authentication
                  codes.
                </li>
              </ul>
            </div>
            <div className="bg-white dark:bg-slate-800 border border-[#e9eff1] dark:border-slate-700 rounded-xl p-6">
              <h4 className="font-bold text-[#101719] dark:text-white mb-4 flex items-center gap-2">
                <span className="material-symbols-outlined text-primary">
                  admin_panel_settings
                </span>
                Account Protection
              </h4>
              <ul className="space-y-4">
                <li className="flex gap-3">
                  <span className="material-symbols-outlined text-primary text-sm mt-1">
                    check_circle
                  </span>
                  <div>
                    <p className="text-sm font-bold text-[#101719] dark:text-slate-200">
                      Session Monitoring
                    </p>
                    <p className="text-xs text-[#57818e] dark:text-slate-400">
                      We notify you of any logins from new devices or locations.
                    </p>
                  </div>
                </li>
                <li className="flex gap-3">
                  <span className="material-symbols-outlined text-primary text-sm mt-1">
                    check_circle
                  </span>
                  <div>
                    <p className="text-sm font-bold text-[#101719] dark:text-slate-200">
                      Automatic Logout
                    </p>
                    <p className="text-xs text-[#57818e] dark:text-slate-400">
                      Inactive sessions are automatically closed to prevent
                      unauthorized access.
                    </p>
                  </div>
                </li>
              </ul>
            </div>
            <div className="relative overflow-hidden rounded-xl h-48 bg-gradient-to-br from-primary to-[#2a84a3] p-8 flex flex-col justify-end text-white">
              <div className="absolute top-[-20px] right-[-20px] opacity-20">
                <span className="material-symbols-outlined text-[160px]">
                  verified_user
                </span>
              </div>
              <p className="text-xl font-black leading-tight">
                Identity <br />
                Verified.
              </p>
              <p className="text-xs mt-2 text-white/80">
                Compliance with international research security standards
              </p>
            </div>
          </div>
        </div>
      </main>
    </section>
  );
}
